version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "microappdemo"
s3_bucket = "aws-sam-config-templatesdas"
s3_prefix = "microappdemo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["microappdemoFunction=348550191801.dkr.ecr.us-east-1.amazonaws.com/microappdemo"]

[DEV]
[DEV.deploy]
[DEV.deploy.parameters]
stack_name = "microappdemo"
s3_bucket = "aws-sam-config-templatesdas"
s3_prefix = "microappdemo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["microappdemoFunction=348550191801.dkr.ecr.us-east-1.amazonaws.com/microappdemo"]
